In [1]:
from sklearn.cluster import KMeans
import numpy as np

In [ ]:
X = np.array([[1, 2], [1, 4], [1, 0],
               [4, 2], [4, 4], [4, 0]])
X = np.array([(-3, -3), (-1, -3), (3, 0), (-2, -1), (0, 0), (-1, -2)])
>>> kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
>>> kmeans.labels_
array([0, 0, 0, 1, 1, 1], dtype=int32)
>>> kmeans.predict([[0, 0], [4, 4]])
array([0, 1], dtype=int32)
>>> kmeans.cluster_centers_

In [5]:
X = np.array([[-3, -3], [-1, -3], [3, 0], [-2, -1], [0, 0], [-1, -2]])

In [7]:
kmeans = KMeans(n_clusters=2, init=np.array([[-1,-3], [-1,-2]])).fit(X)

/anaconda3/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:896: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


In [8]:
kmeans.labels_

array([0, 0, 1, 0, 1, 0], dtype=int32)

In [9]:
kmeans.cluster_centers_

array([[-1.75, -2.25],
       [ 1.5 ,  0.  ]])